### ISSUE TITLE
I don't hear five test tones

### ISSUE THREAD

**Issue by adiantek** [OpenShot/libopenshot-audio#130]
I added .exe to upload-artifacts directly from your repo, added zlib1, libwinpthread, libstdc++, etc. from OpenShot lib directory and I don't hear anything. I don't see app in mixer, too.

**Comment by ferdnyc** [comment]
@adiantek 

From your report, I'm guessing you're on Windows? The test tool doesn't work on Windows, it was never really considered a priority to figure out why. My guess is that it has something to do with the default device either not being set, or being set wrong.

The `testapp-details branch in my fork (https://github.com/ferdnyc/libopenshot-audio/) has added code to also display the default device parameters, in addition to the device probe. It works on Linux, I'm still setting up to build it on Windows. But that may shed some light.

Regardless, the short-short answer is, "That's expected, when running on Windows platforms."

**Comment by adiantek** [comment]
Thanks for letting me know about that. I compiled this to arm64 using MSVCand didn't hear anything, firstly I thought it's sth wrong with my modifications to arm64, then I tested on x64 and still didn't hear. So, I will try compile dependencies of libopenshot to arm64 in free time.

**Comment by ferdnyc** [comment]
Huh? Interesting.

I have now built and run that code on Windows, and as I suspected the issue is that no audio device is open. The interesting thing is that the device _type_ being used by default is shown as "Windows Audio" -- a type for which no devices are discovered. (Presumably because the tool is built as a console program, not a Win32 binary.) JUCE, however, still defaults to WinAudio, and thus finds no device.

There may be a way to convince it to use DirectSound as the default type, which would presumably allow it to find a default device.
