### ISSUE TITLE
Openshot does not build on musl or arm.

### ISSUE THREAD

**Issue by Spencer-H** [OpenShot/libopenshot-audio#2]
ARM: The cmake file that libopenshot-audio (and probably the other openshot projects, though I have not tested them) does not correctly locate freetype ( <ft2build.h> ) when compiling on arm.

On musl: The build fails because of the usage of <execinfo.h> after a little research I discovered that libunwind seems to provide the same functionality without the use of glibc, and with minimal pain of transitioning. (There are other errors as well so I'll include this: http://pastebin.com/sUV6zciA )

**Comment by ferdnyc** [comment]
I can't comment on "musl" since I've never _heard_ of it before, but RPM Fusion has been builing libopenshot-audio on armhfp / armv7hl with no issues. 

Regardless, the Freetype dependency is no longer present in the JUCE code, so that can be removed from the `CMakeLists.txt`. (That's already been switched to using CMake's `FindFreetype.cmake` module, which may do a better job at finding the not-actually-necessary dependency.)

**Comment by ferdnyc** [comment]
I'm going to close this, since as I said ARM building works on the RPM Fusion builders (and libopenshot-audio's build configs no longer contain any traces of freetype or any of the other graphical dependencies), so that should be solved. 

As far as the musl platform, if the compiler is balking on something as basic as the `int64_t` type, I doubt it can be supported by JUCE. Sorry.
