### ISSUE TITLE
Does this library support recording sounds played by other software?

### ISSUE THREAD

**Issue by darkgirl** [OpenShot/libopenshot-audio#72]
recently, i am looking for a cross platform audio library that can record sounds played by other software.
Does this library support? or if you know some other library please tell me, thanks very much.

**Comment by ferdnyc** [comment]
@darkgirl 

libopenshot-audio is really just a subset of the [JUCE audio library](juce.com) functionality, tailored to the specific needs of OpenShot (actually, of its own libopenshot). So, libopenshot-audio definitely can't record system audio, since that functionality wasn't needed and wouldn't have been included. 

But JUCE probably can, at least to whatever extent it's made possible / permitted by the operating system. It's definitely worth checking out.

**Comment by darkgirl** [comment]
> @darkgirl
> 
> libopenshot-audio is really just a subset of the [JUCE audio library](juce.com) functionality, tailored to the specific needs of OpenShot (actually, of its own libopenshot). So, libopenshot-audio definitely can't record system audio, since that functionality wasn't needed and wouldn't have been included.
> 
> But JUCE probably can, at least to whatever extent it's made possible / permitted by the operating system. It's definitely worth checking out.

thank you very much for your very detailed answer
