### ISSUE TITLE
Audio processing/filtering using LV2 plugins?

### ISSUE THREAD

**Issue by mxmilkb** [OpenShot/libopenshot-audio#73]
I think it's fair to say that LV2 is the "primary" audio plugin format on the Linux platform. Enabling the processing of audio tracks by LV2 plugins from within OpenShot would allow for a great variety of creative opportunities.

Related links:
* http://lv2plug.in
* https://github.com/drobilla/lv2/wiki

**Comment by ferdnyc** [comment]
> I think it's fair to say that LV2 is the "primary" audio plugin format on the Linux platform.

True, though that's more by default than anything else. It's not hard to be the best in _that_ field, the "competition" is scoring Own Goals.

> Enabling the processing of audio tracks by LV2 plugins from within OpenShot would allow for a great variety of creative opportunities.

In an ideal world it'd be lovely, sure, but in **this** world there are a few issues I'm afraid:

1. `libopenshot-audio` is cross-platform, LV2 is not. We'd have a rough time justifying LV2 plugin support on Linux without also including VST and AudioUnit support for _those_ platforms, which then becomes triple the maintenance burden.
2. [JUCE](https://juce.com/) has no LV2 support, and no plans to add it. There is [a fork](https://github.com/DISTRHO/juce) started back in 2011 that adds LV2, but that's not kept up with the original project. (We're currently using JUCE 5.4.3, the fork is still at version 5.1.2.)
3. Like VST and AudioUnit plugins, LV2 plugins include a GUI. The primary consumer for libopenshot-audio is OpenShot, a Python application with a Qt interface written in PyQt5, interfacing with libopenshot using SWIG-generated Python bindings, and interfacing with libopenshot-audio not at all (directly). I'm not sure how an external plugin GUI even gets integrated into that stack, honestly. At the very least it would probably require incorporating a lot of the JUCE GUI modules, all of which we actually stripped out last update to streamline the code.
4. In its current form OpenShot's realtime (preview) playback performance is already so poor, under pretty much any conditions (including ideal ones), I can't imagine the additional latency and resource consumption caused by integrating plugin-based audio processing would result in anything that even qualifies as _usable_.

**Comment by mxmilkb** [comment]
1. I wasn't saying LV2 was Linux specific, more implying that LV2 is 'the' libre plugin format. There are Windows builds of various LV2 plugins available, collections from DISTRHO, Zam, x42 and Harrison, and with Carla, Ardour and Audacity, and Windows hosts. I've not checked regarding Mac yet, though Carla and Ardour work on that.
2. Yeah, that's a sticky issue :/ Aside; I just saw [this](https://linuxmusicians.com/viewtopic.php?f=44&t=20584) thread on LM. But maybe there is a way to host LV2 plugins using [other methods](https://github.com/drobilla/lv2/wiki#lv2-hosts).
3. The format allows metadata on port properties for hosts to generate their own UI for settings. Carla does this for both [rack](https://kx.studio/screenshots/news/carla-2.0-beta5_carla-control.png) and [dialog window](https://imgur.com/a/IKRQwlh) (excuse the font bug) formats. Mixxx also now [allows LV2 plugins](https://www.mixxx.org/wiki/doku.php/lv2_support) parameters to be exposed in the UI as dials (no screenshot atm).
4. Hardware will catch up (or is currently expensive). Also, maybe offline processing of longer segments, with snippet previews when choosing the plugin to insert?
