### ISSUE TITLE
Update JUCE to 5.x and trim modules down

### ISSUE THREAD

**Issue by RichiCoder1** [OpenShot/libopenshot-audio#9]
Howdy! 

The version of JUCE being used here is pretty old and has a lot of perf & stability improvements waiting post upgrade. I also reviewed the EULA for Juce 5, and if you trimmed down the modules to the ones libopenshot (appears to be) actually using, this repository could be relicensed as ISC and libopenshot (and it's consumers) would no longer be violating the GPL.

[JUCE License](https://juce.com/juce-5-license)

> Five JUCE modules (juce_core, juce_audio_devices, juce_audio_basics, juce_event, juce_blocks) are licensed under the permissive ISC License as described in this Agreement.

I'd be willing to undertake this work if you'd like :)

**Comment by RichiCoder1** [comment]
So, down that path lies madness. Might still be worth trimming modules though

**Comment by ferdnyc** [comment]
Madness embraced! The JUCE 5 upgrade is done as of #37 / #39.

In the end, I decided to pull that trigger for purely practical reasons: the **old** JUCE code would no longer build under GCC 9. But your initial forays were definitely most informative, in pointing the way to making this happen. I believe this can be closed?

(Also, that being said, I don't believe libopenshot-audio was ever violating the GPL. The ISC license isn't GPL compatible in the first place, but that's OK because:
> During the term of this Agreement, you expressly acknowledge and agree that if you are a JUCE Personal, JUCE Indie, JUCE Pro, or JUCE Education user and the Revenue Limit thresholds, above, are exceeded, then you may no longer use that tier of the Program, and you must either: (a) purchase a different JUCE licence (if eligible); (b) destroy all copies of the Program in your possession or control, and cease distributing your Applications; or in the case of JUCE Personal, or (c) license your Applications under the GNU License. 

libopenshot-audio has taken option (c), licensing JUCE under the GPL _instead of_ the ISC.)
